### ISSUE TITLE
CountryValidation: remove COUNTRY_ prefix from the constants

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1036]
The puzzle `927-f2ec4620` from #927 has to be resolved: 

https://github.com/php-coder/mystamps/blob/04316e62c7d7aa892710479b7b17d45233e9891a/src/main/java/ru/mystamps/web/feature/country/CountryValidation.java#L22-L22

The puzzle was created by Slava Semushin on 08-Jun-19.

**Comment by php-coder** [comment]
_(There was a glitch and GitHub showed that some issue was still open on the list of the issues for 0.4.1 milestone. At the same time, GitHub didn't show what exactly issue still open. It has turned out that it was this issue. I reopen and close it again, so now milestone statistics is shown correctly.)_
