### ISSUE TITLE
Reduce number of collaborators on GitHub

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1050]
We have 19 collaborators and most of them aren't active. Because collaborator's status grants some privileges for php-coder/mystamps repository, reducing number of collaborators potentially could protect the repo against malicious access in case one of the collaborators loose their credentials.

@mihnayan @aarexer @cssru @Shagbark @KrivenkoAlexander @AleksSPb @Smetanin @serg-m @flexjoy @bodom91 @Tachkin @azorinmsu @benjiyue @EarlyM @Shkarin @olithin @n583wxdh0j @MainStar @VitaliAkulau Guys and gals, if you have plans to continue to contribute to this repository, please, leave a comment. Otherwise, **in a 1 month, I'll revoke the collaborator access** from your accounts.

If you don't reply, it means that you don't mind to loose the collaborator's access. You can get it back anytime later, when start contributing again.

Thank you for all your help anyway!

**Comment by MainStar** [comment]
Hi! Yeah I would like to start (or continue) work on project.15.06.2019, 19:35, "Slava Semushin" <notifications@github.com>:We have 19 collaborators and most of them aren't active. Because collaborator's status grants some privileges for php-coder/mystamps repository, reducing number of collaborators potentially could protect the repo against malicious access in case one of the collaborators loose their credentials.
@mihnayan @aarexer @cssru @Shagbark @KrivenkoAlexander @AleksSPb @Smetanin @serg-m @flexjoy @bodom91 @Tachkin @azorinmsu @benjiyue @EarlyM @Shkarin @olithin @n583wxdh0j @MainStar @VitaliAkulau Guys and gals, if you have plans to continue to contribute to this repository, please, leave a comment. Otherwise, in a 1 month, I'll revoke the collaborator access from your accounts.
If you don't reply, it means that you don't mind to loose the collaborator's access. You can get it back anytime later, when start contributing again.
Thank you for all your help anyway!

**Comment by php-coder** [comment]
One month has passed. I'm going to cleanup the list of collaborators now.

You can join back anytime! Thank you!

**Comment by php-coder** [comment]
Done.
