### ISSUE TITLE
CountryController: remove dependency on SeriesService by moving showInfoBySlug() method

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1052]
The puzzle `927-4ad1152b` from #927 has to be resolved: 

https://github.com/php-coder/mystamps/blob/6fc61a2d20b5b13f4eb9a47e5b6f45267f5b11c2/src/main/java/ru/mystamps/web/feature/country/CountryController.java#L88-L88

The puzzle was created by Slava Semushin on 16-Jun-19.

**Comment by mukeshk** [comment]
So in CountryController - showInfoBySlug method internally uses -> seriesService.findByCountrySlug .
When we say we need to move to showInfoBySlug method. 
Do we need to move the showInfoBySlug method to SeriesService? 

Can you elaborate? Thanks.

**Comment by php-coder** [comment]
Note that you shouldn't work on this issue yet because I've realized that it's not so easy to fix it as I thought before.

> So in CountryController - showInfoBySlug method internally uses -> seriesService.findByCountrySlug . When we say we need to move to showInfoBySlug method. Do we need to move the showInfoBySlug method to SeriesService?

The idea was to move the method showInfoBySlug() from CountryController  to SeriesController. But I realized that it's not I really want as it won't fix the issue really.

**Comment by php-coder** [comment]
In order to give you overall understanding on what is all about: I'm trying to split everything by features (country, category, series, collection, etc). All the classes that belong to a feature should be placed into the same package.

Also we shouldn't have circular dependencies between packages. For example, package "country" shouldn't depend on a package "series" because the latter already depend on the "country" package. That's why I had idea to move this method to SeriesController because it uses SeriesService and we have a dependency on "series" package.

But I don't like a fact that SeriesController will have an endpoint for "/country/{slug}" URL. It seems a little weird. So, that's why I cancelled a work on this issue for a while.

**Comment by php-coder** [comment]
At this moment, I have an idea to introduce an endpoint on SeriesController and make CountryController to fetch data from SeriesController.

For example, here is how it looks like now:
/country/{slug} -> CountryController -> SeriesService -> SeriesDao

The proposal is to make it looks like:
/country/{slug} -> CountryController -> /series?country=slug -> SeriesController -> SeriesService -> SeriesDao

But it still not perfect as SeriesService/ServiceDao work with `country` table that doesn't belong to "series" at all. So, another idea is to resolve country slug to country id on CountryController and modify SeriesController to accept countryId instead of country slug:

/country/{slug} -> CountryController -> /series?country_id=$id -> SeriesController -> SeriesService -> SeriesDao

Here is what I'm thinking about now. I'll be happy if you have ideas on that.

**Comment by php-coder** [comment]
Another idea: `/country/{slug}` should be renamed to `/series?country={slug}` and this endpoint can be moved to SeriesController then.
