### ISSUE TITLE
Add integration tests for search by a catalog in user's collection

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1097]
The puzzle `673-67e9da55` from #673 has to be resolved: 

https://github.com/php-coder/mystamps/blob/9778afa44b79fc8d8a65d70aec6793c873b76434/src/main/webapp/WEB-INF/views/site/index.html#L185-L185

The puzzle was created by Mukesh Katariya on 22-Jul-19.

**Comment by mukeshk** [comment]
How do we enable the feature in the test case?

**Comment by php-coder** [comment]
That's a good question, let's enable it then! (To make life easier to us.)

**Comment by mukeshk** [comment]
**-search\access**
`An Anonymous user cannot request search in his collection
	Page Should Not Contain Element  id=in-collection

An Authorized user can request search in his collection
	Log In As						 login=admin  password=test
	Page Should Not Contain Element  id=in-collection`

**- search\validation** 

`Search in my collection is unchecked on load
	Log In As						 login=admin  password=test
    Checkbox Should Not Be Selected  id=in-collection`

**Comment by mukeshk** [comment]
What would be the test data set for "no search result"  in my collection?
- admin/test - any catalogue - result in no result/
What would be the test data set for "search result" to have some data for in my collection search?

**Comment by mukeshk** [comment]
Please suggest

**Comment by php-coder** [comment]
@mukeshk I'm looking on it right now :)

**Comment by php-coder** [comment]
1) we need to test the same cases as we have for an anonymous user -- nothing found and something found. No need to test anything else
2) let's put these cases into `src/test/robotframework/series/search/logic-user.robot`
3) let's use user "coder" user for tests (not "admin")

> What would be the test data set for "no search result" in my collection?

use the same data as for anonymous user (just copy&paste + we need to check a checkbox)

> What would be the test data set for "search result" to have some data for in my collection search?

use the same data as for anonymous user (just copy&paste + we need to check a checkbox) -- it should work AFAIR because user "coder" has series #1 in his collection

**Comment by mukeshk** [comment]
with coder/test account.
I am looking for a CatalogName and CatalogNumber for which I will get the result when I check "in my collection" and "no result" when checked is false.

So the test case differs only in checkbox flag.
What is the Catalog Name and Number for this test case scenario?

**Comment by php-coder** [comment]
> So the test case differs only in checkbox flag.

Actually, no. The checkbox is always selected. They differ by catalog name/number.

> What is the Catalog Name and Number for this test case scenario?

That's a great question! I've checked and see that "coder" has no series in his collection. That means that we can't use this user for this test and have to create another one.

So, we need:
1) create a test user who has series with id=1 in this collection
2) add 2 test cases similar to `Search series by non-existing catalog number` and `Search series by existing catalog number` but with checkbox activated

Let me know if you need help/guidance here.

**Comment by mukeshk** [comment]
1.create a test user who has series with id=1 in this collection
   How do we do this? I see something in test-data.properties but not fully aware of how it translates into SQL scripts?

Also, can you put together something on the data model - any diagram, data dictionary to explain the DB design. Not immediately though :).

**Comment by php-coder** [comment]
Thanks for the response! There 2 ways -- slow (when you wait the full instructions) and a little faster (where I give you pointers, you try, I help you to remove roadblocks and after few iterations we have make it working). Which one do you prefer?

**Comment by mukeshk** [comment]
I will prefer the faster one, I will love to work my way through understand
things.

Unless you prefer to start some other task.

**Comment by php-coder** [comment]
So, the first step is to add a test user that will have a series in his collection. We need to add a new database migration.

- here is an example on how to create a user and his collection:
https://github.com/php-coder/mystamps/blob/3914aa1fa34b9a2148ee99ae445248e6886dd15d/src/main/resources/liquibase/version/0.4/2017-01-06--top_categories.xml#L59-L72
Here we need a real hash for password in order to be able to log in later. Let's use `valid_user_password_hash` from `test-data.properties`

- in order to add a series to user's collection, we need to add a record to `collections_series` table.

If you want to play with database, try the following:
- open `http://localhost:8080/console`
- use "org.h2.Driver" as the driver
- use "jdbc:h2:mem:mystamps" as the URL
- use "sa" as the username and a blank password

There you will see the current state of database, all the tables and you might play with queries in order to make everything work.

**Comment by mukeshk** [comment]
1. I have created a new User.
2. I have created a new Collection.
3. I have created a record in collection_series with an existing series.

I build a SQL script by looking at other scripts. 
I assume I need to put the SQL under 0.4.1 version in liquibase.

Am I correct?
Apologize for the delay was stuck in some other work.

**Comment by php-coder** [comment]
Yes, everything sounds good. Let's continue the discussion in PR ;-)
