### ISSUE TITLE
WhenAnonymousUserRegisterAccount.emailWithActivationKeyShouldBeSentAfterRegistration(): may fails on slow machines

### ISSUE THREAD

**Issue by TMTQuant** [php-coder/mystamps#428]
If after running integration tests you can see error message like `emailWithActivationKeyShouldBeSentAfterRegistration` 
Open and edit this file `%project_folder%\src\test\java\ru\mystamps\web\tests\cases\WhenAnonymousUserRegisterAccount.java
`
You need to make constant number on line 57 a bit bigger 
`private static final int MAX_TIME_TO_WAIT_EMAIL_IN_SECONDS = 5;`
In my case, 15 is enough

**Comment by php-coder** [comment]
I suppose that your machine is slow, isn't it? How much RAM/CPU do you have?

**Comment by TMTQuant** [comment]
Yes, my machine can be slow because it`s a laptop
Core i5 2.8GHz
8.00 RAM

**Comment by php-coder** [comment]
Your laptop doesn't looks like a slow :) Probably there is something else. Is it always reproducible? Did you see something unusual in the logs output?

**Comment by TMTQuant** [comment]
Every time when i set value between 5-10 i had such problem. I dunno but it can be slowly cuz i have really bad internet connection and a lot of probramm`s working backgroung.  Nothing unusual in logs what can relate to this message

**Comment by php-coder** [comment]
Let's increase the value of `MAX_TIME_TO_WAIT_EMAIL_IN_SECONDS` to 15 then.

**Comment by benjiyue** [comment]
Out of curiosity, what exactly was being tested here and why did slower computers fail with the old timeout?

**Comment by php-coder** [comment]
First of all, it's good that you're asking questions like these.

> what exactly was being tested here

I hope that you have already tried to read the test sources :) In short, when user is registering on the site, the server sends an e-mail to him with the activation code. That is what we're testing here. To be able to get access to this e-mail, we're setting up our own SMTP-server in the beginning of the test. In this case, the server connects to our own SMTP-server and this allows us to get this e-mail from our SMTP-server. Within the test, we're polling SMTP-server each second, as far I remember. To prevent infinity polling we have a timeout, that you've increased here.

> and why did slower computers fail with the old timeout?

To be honest, I don't know. It wasn't reproducible on my computer and I didn't have a chance to debug it deeper. I even don't think that it happens because of slow computer. Most likely it's because of the network configuration. But if it worked for @TMTQuant, why not increase this timeout? :) This affects only a case when this test fails and in this case it will fail not after 5 seconds but after 15.
