### ISSUE TITLE
Series import: validate app.site-parser[x].currency-value

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#842]
The puzzle `695-707db4aa` from #695 has to be resolved:

https://github.com/php-coder/mystamps/blob/df45acd6abca61c1d2c1c9174dff0312e095d5fa/src/main/java/ru/mystamps/web/util/extractor/JsoupSiteParser.java#L108-L108

The puzzle was created by Slava Semushin on 04-Jan-18. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by php-coder** [comment]
After fixing #975 the properties will live in database and we won't have code that validates the properties (see also #751). I'm not sure that we need validation for them at this stage because such errors should not happen as only admin adds these properties to database. Even if they occurs, the chance is really small and in that case we may circle back to this discussion.
