### ISSUE TITLE
/collection/{slug}/estimation: admin should have access to everyone's estimation page

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#889]
The puzzle `884-61920ac4` from #884 has to be resolved:

https://github.com/php-coder/mystamps/blob/9287473f424222a3ead476ee7be30960c2c6dfcf/src/main/java/ru/mystamps/web/support/spring/security/SecurityConfig.java#L92-L92

The puzzle was created by Slava Semushin on 20-Jun-18.

**Comment by php-coder** [comment]
At this moment the task is already solved: "only owner should have access to estimation page" statement is true because in #891 we restricted the access to the service method by only collection's owner. Even if the access on the page-level aren't so strict, the page can't be opened anyway because the service method has a stricter protection. See https://github.com/spring-projects/spring-security/issues/6948 for details.

But the access still needs to be altered to allow admin access to everyone's page. This should simplify debug when it will be required. So, I've edited the issue's title to reflect that.
